export interface Venue {
  id: string;
  name: string;
  neighborhood: string;
  area: "San Francisco" | "Peninsula" | "South Bay" | "East Bay";
  address: string;
  capacityMin: number;
  capacityMax: number;
  eventTypes: EventType[];
  priceLevel: 1 | 2 | 3 | 4;
  highlights: string[];
  description: string;
  website: string;
  imageQuery: string;
}

export type EventType =
  | "Executive Dinner"
  | "Networking"
  | "Product Launch"
  | "Conference"
  | "Offsite"
  | "Workshop"
  | "Hackathon"
  | "Meetup";

export type Area = Venue["area"];

export const EVENT_TYPES: EventType[] = [
  "Executive Dinner",
  "Networking",
  "Product Launch",
  "Conference",
  "Offsite",
  "Workshop",
  "Hackathon",
  "Meetup",
];

export const AREAS: Area[] = [
  "San Francisco",
  "Peninsula",
  "South Bay",
  "East Bay",
];

export const venues: Venue[] = [
  {
    id: "shack15",
    name: "Shack15",
    neighborhood: "Embarcadero",
    area: "San Francisco",
    address: "1 Ferry Building, Suite 2, San Francisco, CA 94111",
    capacityMin: 50,
    capacityMax: 300,
    eventTypes: ["Meetup", "Networking", "Product Launch", "Workshop"],
    priceLevel: 3,
    highlights: [
      "Floor-to-ceiling bay views",
      "Built-in AV & presentation tech",
      "Members club atmosphere",
      "Steps from BART",
    ],
    description:
      "A tech-forward members club inside the Ferry Building with panoramic bay views. The flexible floor plan works for intimate roundtables or standing-room launches. Popular with AI startups for demo days and investor events.",
    website: "https://www.shack15.com",
    imageQuery: "shack15-ferry-building",
  },
  {
    id: "the-pearl",
    name: "The Pearl",
    neighborhood: "Dogpatch",
    area: "San Francisco",
    address: "601 19th St, San Francisco, CA 94107",
    capacityMin: 100,
    capacityMax: 500,
    eventTypes: ["Conference", "Product Launch", "Networking", "Offsite"],
    priceLevel: 3,
    highlights: [
      "Industrial-chic warehouse",
      "20-foot ceilings",
      "Full production capabilities",
      "On-site catering kitchen",
    ],
    description:
      "A converted Dogpatch warehouse with soaring ceilings and polished concrete floors. The raw industrial aesthetic pairs well with tech events. Fully customizable with staging, lighting, and AV built in.",
    website: "https://www.thepearlsf.com",
    imageQuery: "the-pearl-sf-dogpatch",
  },
  {
    id: "terra-gallery",
    name: "Terra Gallery",
    neighborhood: "SoMa",
    area: "San Francisco",
    address: "511 Harrison St, San Francisco, CA 94105",
    capacityMin: 200,
    capacityMax: 800,
    eventTypes: ["Conference", "Product Launch", "Networking"],
    priceLevel: 4,
    highlights: [
      "10,000 sq ft main gallery",
      "Rotating art installations",
      "Multiple configurable rooms",
      "Award-winning event space",
    ],
    description:
      "A stunning SoMa gallery that blends art and architecture. The versatile layout supports large keynotes, breakout sessions, and cocktail receptions simultaneously. A go-to for major product launches in the AI space.",
    website: "https://www.terrasf.com",
    imageQuery: "terra-gallery-sf",
  },
  {
    id: "computer-history-museum",
    name: "Computer History Museum",
    neighborhood: "Mountain View",
    area: "South Bay",
    address: "1401 N Shoreline Blvd, Mountain View, CA 94043",
    capacityMin: 100,
    capacityMax: 1000,
    eventTypes: ["Conference", "Product Launch", "Networking", "Meetup"],
    priceLevel: 3,
    highlights: [
      "Iconic tech venue",
      "Museum exhibit access for guests",
      "Large outdoor courtyard",
      "Adjacent to Google campus",
    ],
    description:
      "The symbolic home of Silicon Valley's history. Host your event surrounded by computing artifacts spanning decades. The main hall and outdoor courtyard provide a uniquely resonant backdrop for AI company milestones.",
    website: "https://computerhistory.org/rentals",
    imageQuery: "computer-history-museum-mountain-view",
  },
  {
    id: "the-hibernia",
    name: "The Hibernia",
    neighborhood: "Civic Center",
    area: "San Francisco",
    address: "1 Jones St, San Francisco, CA 94102",
    capacityMin: 200,
    capacityMax: 600,
    eventTypes: ["Conference", "Product Launch", "Executive Dinner"],
    priceLevel: 4,
    highlights: [
      "Beaux-Arts architecture",
      "Grand banking hall",
      "Historic landmark building",
      "Dramatic columns & dome",
    ],
    description:
      "A breathtaking 1892 bank building transformed into one of SF's most dramatic event spaces. The grand banking hall with its soaring dome and Corinthian columns creates an unforgettable setting for keynotes and galas.",
    website: "https://www.thehiberniasf.com",
    imageQuery: "hibernia-bank-sf",
  },
  {
    id: "fort-mason-center",
    name: "Fort Mason Center",
    neighborhood: "Marina",
    area: "San Francisco",
    address: "2 Marina Blvd, San Francisco, CA 94123",
    capacityMin: 50,
    capacityMax: 2000,
    eventTypes: ["Conference", "Offsite", "Meetup", "Networking"],
    priceLevel: 3,
    highlights: [
      "Waterfront campus",
      "Multiple venue sizes",
      "Golden Gate views",
      "Free parking available",
    ],
    description:
      "A sprawling waterfront campus with venues ranging from intimate meeting rooms to massive pavilions. The combination of bay views, open green space, and historic architecture makes it ideal for multi-day conferences and offsites.",
    website: "https://fortmason.org",
    imageQuery: "fort-mason-center-sf",
  },
  {
    id: "bespoke-events",
    name: "Bespoke Events",
    neighborhood: "SoMa",
    area: "San Francisco",
    address: "845 Market St, Level 4, San Francisco, CA 94103",
    capacityMin: 30,
    capacityMax: 300,
    eventTypes: ["Meetup", "Workshop", "Hackathon", "Product Launch"],
    priceLevel: 2,
    highlights: [
      "Central Market St location",
      "Modular floor plan",
      "Built-in AV & WiFi",
      "On-site event coordination",
    ],
    description:
      "A modern, tech-ready event space in the heart of SoMa. The modular layout adapts from boardroom-style workshops to open networking formats. Turnkey AV and strong WiFi make it a reliable choice for hackathons and demo days.",
    website: "https://www.bespokesf.co",
    imageQuery: "bespoke-events-sf",
  },
  {
    id: "the-midway",
    name: "The Midway",
    neighborhood: "Dogpatch",
    area: "San Francisco",
    address: "900 Marin St, San Francisco, CA 94124",
    capacityMin: 200,
    capacityMax: 1500,
    eventTypes: ["Conference", "Product Launch", "Networking"],
    priceLevel: 3,
    highlights: [
      "40,000 sq ft complex",
      "Indoor & outdoor spaces",
      "Immersive production capabilities",
      "Full bar & kitchen",
    ],
    description:
      "A massive multi-room arts and event complex in Dogpatch. Known for immersive experiences with professional lighting, sound, and projection. The scale and production quality make it a standout for major AI product reveals.",
    website: "https://www.themidwaysf.com",
    imageQuery: "the-midway-sf",
  },
  {
    id: "city-view-metreon",
    name: "City View at Metreon",
    neighborhood: "SoMa",
    area: "San Francisco",
    address: "135 4th St, 4th Floor, San Francisco, CA 94103",
    capacityMin: 50,
    capacityMax: 400,
    eventTypes: ["Networking", "Product Launch", "Executive Dinner"],
    priceLevel: 3,
    highlights: [
      "Rooftop terrace",
      "Downtown skyline views",
      "Adjacent to Moscone Center",
      "Full-service catering",
    ],
    description:
      "An elevated event space atop the Metreon with sweeping views of the SF skyline and Yerba Buena Gardens. The indoor-outdoor flow is perfect for cocktail receptions and seated dinners. A polished choice near Moscone.",
    website: "https://www.cityviewmetreon.com",
    imageQuery: "city-view-metreon-sf",
  },
  {
    id: "palace-of-fine-arts",
    name: "Palace of Fine Arts",
    neighborhood: "Marina",
    area: "San Francisco",
    address: "3601 Lyon St, San Francisco, CA 94123",
    capacityMin: 100,
    capacityMax: 1000,
    eventTypes: ["Conference", "Product Launch", "Executive Dinner"],
    priceLevel: 4,
    highlights: [
      "Iconic rotunda & colonnade",
      "Lagoon-side setting",
      "Theater with 960 seats",
      "SF landmark venue",
    ],
    description:
      "One of San Francisco's most recognizable landmarks. The Greco-Roman rotunda and tranquil lagoon provide a dramatic backdrop. The adjacent theater seats nearly 1,000 and is fully equipped for keynotes and presentations.",
    website: "https://palaceoffinearts.com",
    imageQuery: "palace-fine-arts-sf",
  },
  {
    id: "august-hall",
    name: "August Hall",
    neighborhood: "SoMa",
    area: "San Francisco",
    address: "420 Mason St, San Francisco, CA 94102",
    capacityMin: 200,
    capacityMax: 1000,
    eventTypes: ["Conference", "Product Launch", "Networking"],
    priceLevel: 3,
    highlights: [
      "Historic theater",
      "Professional stage & sound",
      "Balcony & mezzanine levels",
      "Union Square location",
    ],
    description:
      "A beautifully restored historic theater near Union Square. The professional stage, balcony seating, and state-of-the-art sound system make it ideal for keynote-driven events and large product launches.",
    website: "https://www.augusthallsf.com",
    imageQuery: "august-hall-sf",
  },
  {
    id: "the-craneway-pavilion",
    name: "The Craneway Pavilion",
    neighborhood: "Richmond",
    area: "East Bay",
    address: "1414 Harbour Way S, Richmond, CA 94804",
    capacityMin: 500,
    capacityMax: 5000,
    eventTypes: ["Conference", "Offsite", "Product Launch"],
    priceLevel: 3,
    highlights: [
      "75,000 sq ft open floor",
      "Floor-to-ceiling bay windows",
      "Historic Ford assembly plant",
      "Waterfront with Mt. Tam views",
    ],
    description:
      "A massive waterfront venue in a converted Ford assembly plant. The column-free floor and panoramic bay windows create an awe-inspiring setting for large-scale conferences. One of the biggest and most dramatic venues in the Bay Area.",
    website: "https://www.craneway.com",
    imageQuery: "craneway-pavilion-richmond",
  },
  {
    id: "dogpatch-studios",
    name: "Dogpatch Studios",
    neighborhood: "Dogpatch",
    area: "San Francisco",
    address: "991 Tennessee St, San Francisco, CA 94107",
    capacityMin: 50,
    capacityMax: 300,
    eventTypes: ["Workshop", "Meetup", "Product Launch", "Hackathon"],
    priceLevel: 2,
    highlights: [
      "Natural light studios",
      "Blank-canvas versatility",
      "Loading dock access",
      "Adjacent outdoor patio",
    ],
    description:
      "A collection of daylight studios in the heart of Dogpatch. The raw, adaptable spaces work for everything from intimate workshops to pop-up product showcases. Popular with startups for its creative energy and reasonable pricing.",
    website: "https://www.dogpatchstudios.com",
    imageQuery: "dogpatch-studios-sf",
  },
  {
    id: "san-francisco-mint",
    name: "The San Francisco Mint",
    neighborhood: "SoMa",
    area: "San Francisco",
    address: "88 5th St, San Francisco, CA 94103",
    capacityMin: 200,
    capacityMax: 800,
    eventTypes: ["Conference", "Product Launch", "Executive Dinner", "Networking"],
    priceLevel: 4,
    highlights: [
      "1874 granite landmark",
      "Grand neoclassical interiors",
      "Multiple event rooms",
      "Survived the 1906 earthquake",
    ],
    description:
      "A granite neoclassical landmark that survived the 1906 earthquake. The restored interiors — vaulted ceilings, marble floors, and historic vaults — provide an unmatched setting for premium events. A truly unique SF venue.",
    website: "https://www.sfmint.org",
    imageQuery: "old-mint-sf",
  },
  {
    id: "pier-27",
    name: "Pier 27",
    neighborhood: "Embarcadero",
    area: "San Francisco",
    address: "Pier 27, The Embarcadero, San Francisco, CA 94111",
    capacityMin: 500,
    capacityMax: 2000,
    eventTypes: ["Conference", "Product Launch"],
    priceLevel: 4,
    highlights: [
      "60,000 sq ft waterfront",
      "Bay Bridge & Treasure Island views",
      "Column-free floor plan",
      "San Francisco's cruise terminal",
    ],
    description:
      "San Francisco's premier waterfront event facility at the cruise terminal. The massive, column-free space with bay views through floor-to-ceiling windows is built for large-scale conferences and landmark product launches.",
    website: "https://www.pier27sf.com",
    imageQuery: "pier-27-sf",
  },
  {
    id: "swedish-american-hall",
    name: "Swedish American Hall",
    neighborhood: "Castro",
    area: "San Francisco",
    address: "2174 Market St, San Francisco, CA 94114",
    capacityMin: 50,
    capacityMax: 400,
    eventTypes: ["Meetup", "Networking", "Workshop"],
    priceLevel: 2,
    highlights: [
      "1907 historic hall",
      "Intimate balcony seating",
      "Full bar (Café du Nord below)",
      "Hardwood floors & stage",
    ],
    description:
      "A charming 1907 hall above Café du Nord with a warm, intimate atmosphere. The balcony level and classic stage setup work well for speaker-driven meetups and community events. Great acoustics and character.",
    website: "https://www.swedishamericanhall.com",
    imageQuery: "swedish-american-hall-sf",
  },
  {
    id: "ameswell-hotel",
    name: "Ameswell Hotel",
    neighborhood: "Mountain View",
    area: "South Bay",
    address: "800 Moffett Blvd, Mountain View, CA 94043",
    capacityMin: 20,
    capacityMax: 200,
    eventTypes: ["Executive Dinner", "Offsite", "Workshop"],
    priceLevel: 3,
    highlights: [
      "Modern boutique hotel",
      "Near NASA Ames & Google",
      "Indoor-outdoor event spaces",
      "Guest rooms for multi-day events",
    ],
    description:
      "A sleek boutique hotel near NASA Ames Research Center and the Googleplex. The combination of modern meeting rooms, a restaurant, and guest rooms makes it a seamless choice for executive offsites and multi-day workshops.",
    website: "https://www.ameswellhotel.com",
    imageQuery: "ameswell-hotel-mountain-view",
  },
  {
    id: "oakland-museum",
    name: "Oakland Museum of California",
    neighborhood: "Downtown Oakland",
    area: "East Bay",
    address: "1000 Oak St, Oakland, CA 94607",
    capacityMin: 100,
    capacityMax: 1500,
    eventTypes: ["Conference", "Networking", "Product Launch", "Offsite"],
    priceLevel: 3,
    highlights: [
      "Terraced garden architecture",
      "Museum galleries as backdrop",
      "Indoor & outdoor spaces",
      "Steps from Lake Merritt BART",
    ],
    description:
      "A Brutalist architectural gem with terraced rooftop gardens overlooking Lake Merritt. The galleries, courtyards, and event halls offer a rich, curated atmosphere. A distinctive East Bay alternative to SF venues.",
    website: "https://museumca.org/facility-rental",
    imageQuery: "oakland-museum-california",
  },
  {
    id: "quadrus-conference-center",
    name: "Quadrus Conference Center",
    neighborhood: "Menlo Park",
    area: "Peninsula",
    address: "2400 Sand Hill Rd, Menlo Park, CA 94025",
    capacityMin: 20,
    capacityMax: 150,
    eventTypes: ["Executive Dinner", "Workshop", "Offsite"],
    priceLevel: 3,
    highlights: [
      "Sand Hill Road address",
      "VC corridor location",
      "Landscaped courtyards",
      "Premium boardroom facilities",
    ],
    description:
      "Nestled on Sand Hill Road among the biggest names in venture capital. The intimate conference rooms and manicured grounds are tailor-made for executive gatherings, investor meetings, and strategy offsites.",
    website: "https://www.quadrus.com",
    imageQuery: "quadrus-conference-center-menlo-park",
  },
  {
    id: "impact-hub-oakland",
    name: "Impact Hub Oakland",
    neighborhood: "Downtown Oakland",
    area: "East Bay",
    address: "2323 Broadway, Oakland, CA 94612",
    capacityMin: 20,
    capacityMax: 200,
    eventTypes: ["Meetup", "Workshop", "Hackathon", "Networking"],
    priceLevel: 1,
    highlights: [
      "Community-driven space",
      "Affordable rates",
      "Modular room setup",
      "Close to 19th St BART",
    ],
    description:
      "A community-focused co-working and event space in downtown Oakland. The accessible pricing and flexible layout make it a natural home for grassroots AI meetups, hackathons, and community workshops.",
    website: "https://oakland.impacthub.net",
    imageQuery: "impact-hub-oakland",
  },
  {
    id: "plug-and-play",
    name: "Plug and Play Tech Center",
    neighborhood: "Sunnyvale",
    area: "South Bay",
    address: "440 N Wolfe Rd, Sunnyvale, CA 94085",
    capacityMin: 50,
    capacityMax: 500,
    eventTypes: ["Meetup", "Conference", "Networking", "Product Launch"],
    priceLevel: 2,
    highlights: [
      "Silicon Valley startup hub",
      "Built-in demo areas",
      "Global accelerator network",
      "Free parking",
    ],
    description:
      "The world's largest startup accelerator campus, purpose-built for tech events. The auditorium and demo areas are designed for pitch days and product showcases. A natural fit for AI startups in the South Bay.",
    website: "https://www.plugandplaytechcenter.com",
    imageQuery: "plug-and-play-sunnyvale",
  },
  {
    id: "the-village",
    name: "The Village",
    neighborhood: "SoMa",
    area: "San Francisco",
    address: "969 Market St, San Francisco, CA 94103",
    capacityMin: 50,
    capacityMax: 350,
    eventTypes: ["Meetup", "Workshop", "Networking", "Product Launch"],
    priceLevel: 2,
    highlights: [
      "Central Market St location",
      "Exposed brick & timber",
      "Green room & breakout spaces",
      "Strong WiFi throughout",
    ],
    description:
      "A warm, loft-style venue on Market Street with exposed brick walls and timber beams. The central location and versatile floor plan make it a convenient mid-size option for meetups, launches, and networking events.",
    website: "https://www.thevillagesf.com",
    imageQuery: "the-village-sf",
  },
  {
    id: "marines-memorial",
    name: "Marines' Memorial Club",
    neighborhood: "Union Square",
    area: "San Francisco",
    address: "609 Sutter St, San Francisco, CA 94102",
    capacityMin: 20,
    capacityMax: 400,
    eventTypes: ["Executive Dinner", "Conference", "Networking", "Offsite"],
    priceLevel: 3,
    highlights: [
      "Historic military club",
      "450-seat theater",
      "Rooftop terrace",
      "Hotel rooms on-site",
    ],
    description:
      "A distinguished Union Square institution with a 450-seat theater, banquet halls, and a rooftop terrace with city views. The on-site hotel rooms make it practical for multi-day conferences and executive retreats.",
    website: "https://www.marinesmemorial.org",
    imageQuery: "marines-memorial-club-sf",
  },
  {
    id: "gallery-308",
    name: "Gallery 308 at Fort Mason",
    neighborhood: "Marina",
    area: "San Francisco",
    address: "Fort Mason Center, Landmark Building A, San Francisco, CA 94123",
    capacityMin: 50,
    capacityMax: 250,
    eventTypes: ["Executive Dinner", "Networking", "Product Launch"],
    priceLevel: 3,
    highlights: [
      "Golden Gate Bridge views",
      "Gallery-style white walls",
      "Natural light",
      "Waterfront terrace",
    ],
    description:
      "A refined gallery space at Fort Mason with unobstructed views of the Golden Gate Bridge. The clean white walls and natural light create a sophisticated backdrop for curated dinners and intimate product reveals.",
    website: "https://fortmason.org/venue/gallery-308",
    imageQuery: "gallery-308-fort-mason",
  },
  {
    id: "rosewood-sand-hill",
    name: "Rosewood Sand Hill",
    neighborhood: "Menlo Park",
    area: "Peninsula",
    address: "2825 Sand Hill Rd, Menlo Park, CA 94025",
    capacityMin: 10,
    capacityMax: 250,
    eventTypes: ["Executive Dinner", "Offsite", "Workshop"],
    priceLevel: 4,
    highlights: [
      "Luxury resort setting",
      "Vineyard & garden views",
      "Premium dining on-site",
      "Preferred by VCs & executives",
    ],
    description:
      "The unofficial living room of Sand Hill Road. This luxury resort is where VC deals get done over dinner. Intimate boardrooms, garden terraces, and a Michelin-adjacent restaurant make it the top choice for high-stakes executive gatherings.",
    website: "https://www.rosewoodhotels.com/en/sand-hill",
    imageQuery: "rosewood-sand-hill-menlo-park",
  },
  {
    id: "public-works",
    name: "Public Works",
    neighborhood: "Mission",
    area: "San Francisco",
    address: "161 Erie St, San Francisco, CA 94103",
    capacityMin: 100,
    capacityMax: 450,
    eventTypes: ["Meetup", "Networking", "Product Launch", "Hackathon"],
    priceLevel: 2,
    highlights: [
      "Multi-level venue",
      "Street art murals",
      "Full sound system",
      "Outdoor patio",
    ],
    description:
      "A vibrant Mission District venue spread across two levels with rotating street art murals. The energetic atmosphere and professional sound system make it a favorite for launch parties and community-driven tech events.",
    website: "https://publicsf.com",
    imageQuery: "public-works-sf",
  },
  {
    id: "david-brower-center",
    name: "David Brower Center",
    neighborhood: "Downtown Berkeley",
    area: "East Bay",
    address: "2150 Allston Way, Berkeley, CA 94704",
    capacityMin: 30,
    capacityMax: 300,
    eventTypes: ["Conference", "Workshop", "Meetup", "Networking"],
    priceLevel: 2,
    highlights: [
      "LEED Platinum certified",
      "Near UC Berkeley campus",
      "Art gallery & event halls",
      "Steps from Downtown Berkeley BART",
    ],
    description:
      "A sustainably designed event space steps from UC Berkeley and BART. The combination of gallery spaces, a theater, and flexible meeting rooms attracts a smart, academic-adjacent crowd. Great for AI research and ethics events.",
    website: "https://browercenter.org",
    imageQuery: "david-brower-center-berkeley",
  },
  {
    id: "cabinet",
    name: "Cabinet",
    neighborhood: "SoMa",
    area: "San Francisco",
    address: "525 Howard St, San Francisco, CA 94105",
    capacityMin: 20,
    capacityMax: 100,
    eventTypes: ["Executive Dinner", "Workshop", "Networking"],
    priceLevel: 3,
    highlights: [
      "Intimate private dining",
      "Award-winning chef",
      "Wine program",
      "Steps from Moscone",
    ],
    description:
      "An upscale private dining venue near Moscone Center with a refined, intimate atmosphere. The chef-driven menus and curated wine program make it ideal for executive dinners and high-touch networking events.",
    website: "https://www.cabinetsf.com",
    imageQuery: "cabinet-sf",
  },
  {
    id: "the-pearl-oakland",
    name: "The Pearl on Broadway",
    neighborhood: "Downtown Oakland",
    area: "East Bay",
    address: "1619 Broadway, Oakland, CA 94612",
    capacityMin: 50,
    capacityMax: 250,
    eventTypes: ["Networking", "Meetup", "Product Launch", "Workshop"],
    priceLevel: 2,
    highlights: [
      "Rooftop bar & patio",
      "Downtown Oakland nightlife",
      "Flexible event floors",
      "Near 19th St BART",
    ],
    description:
      "A multi-level downtown Oakland venue with a popular rooftop bar. The relaxed energy and accessible pricing make it a great choice for community meetups and networking events with a more casual vibe.",
    website: "https://www.thepearldowntown.com",
    imageQuery: "the-pearl-oakland",
  },
];
